#!/bin/bash
set -eu

###########################################################################
### INIT
SERVICE=

###########################################################################
## PARAMETER PARSING
usage() {
cat <<USAGE
Usage: start-service (-s|--service) <serviceName>

Required:
    -s, --service           service name (Required)
USAGE
}

# Parse options
while [[ $# -ne 0 ]]
do
    case "$1" in
        -s|--service)
            SERVICE="${2:-}"
            shift 2
            ;;
        *)
            echo "ERROR: Unknown option: $1" >&2
            usage
            exit 1
            ;;
    esac
done


###########################################################################
### Checking

# Check for missing parameters
[[ -z ${SERVICE} ]] && {
    echo "ERROR: Missing required parameter." >&2
    usage
    exit 1
}

[[ ! -d /var/mcalazans/services/${SERVICE} ]] && {
    echo "ERROR: Service (${SERVICE}) not available." >&2
    exit 1
}
echo "Starting ${SERVICE}"
/usr/local/bin/docker-compose -f /var/mcalazans/services/${SERVICE}/docker-compose.yml up -d